### PR TITLE
Add support for png images

### PR DESCRIPTION
**Pull request by NeeEoo**
This implements #3.

I was unable to get transparency working.

### CODE REVIEW

**Comment by catdad** [comment]
Well that makes me angry at the bmp spec. It has an alpha channel, but everything that I've been able to find seems to confirm that it is in fact never really used. 😞

Oh well, that probably means that there will eventually need to be an option for a blend color. But I guess that doesn't have to happen right now.

**Review by catdad — CHANGES_REQUESTED** [review]
Could you add a test for the new PNG support?

Since we already have `jpeg-js` and `pngjs`, we can just convert the already available jpeg to png and pass that in. Check out the first API test already in the repo.

**Comment by NeeEoo** [comment]
[This works](https://gist.github.com/NeeEoo/6d29e9e43c1c881178e577797c8f4a72) but it's a bit messy.

**Comment by catdad** [comment]
`pngjs` has a `PNG.sync.write` method, so you can just do this and not do any of the unnecessary stream business:

```javascript
    it('converts a png to bmp', async () => {
      const { width, height, data: jpegData } = jpeg.decode(data);
      const png = new PNG({ width, height });
      png.data = jpegData;
      const pngBuffer = PNG.sync.write(png);

      const [error, output] = await lib(pngBuffer);

      expect(error).to.equal(undefined);
      expect(isBmp(output)).to.equal(true, 'output is not a bmp');
      expect(hash(output)).to.equal(HASH);
    });
```

**Comment by NeeEoo** [comment]
Didn't notice that `PNG.sync.write` returned a buffer.

**Review by catdad — APPROVED** [review]

**Pull request merged**
